//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpTempTest.RDCService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RDCService.SelectFromRDCSoap")]
    public interface SelectFromRDCSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorldResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        DevExpTempTest.RDCService.HelloWorldResponse HelloWorld(DevExpTempTest.RDCService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<DevExpTempTest.RDCService.HelloWorldResponse> HelloWorldAsync(DevExpTempTest.RDCService.HelloWorldRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément RubriqueDocumentComptableResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RubriqueDocumentComptable", ReplyAction="*")]
        DevExpTempTest.RDCService.RubriqueDocumentComptableResponse RubriqueDocumentComptable(DevExpTempTest.RDCService.RubriqueDocumentComptableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RubriqueDocumentComptable", ReplyAction="*")]
        System.Threading.Tasks.Task<DevExpTempTest.RDCService.RubriqueDocumentComptableResponse> RubriqueDocumentComptableAsync(DevExpTempTest.RDCService.RubriqueDocumentComptableRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public DevExpTempTest.RDCService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DevExpTempTest.RDCService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public DevExpTempTest.RDCService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DevExpTempTest.RDCService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RubriqueDocumentComptableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RubriqueDocumentComptable", Namespace="http://tempuri.org/", Order=0)]
        public DevExpTempTest.RDCService.RubriqueDocumentComptableRequestBody Body;
        
        public RubriqueDocumentComptableRequest() {
        }
        
        public RubriqueDocumentComptableRequest(DevExpTempTest.RDCService.RubriqueDocumentComptableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RubriqueDocumentComptableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int _latestId;
        
        public RubriqueDocumentComptableRequestBody() {
        }
        
        public RubriqueDocumentComptableRequestBody(int _latestId) {
            this._latestId = _latestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RubriqueDocumentComptableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RubriqueDocumentComptableResponse", Namespace="http://tempuri.org/", Order=0)]
        public DevExpTempTest.RDCService.RubriqueDocumentComptableResponseBody Body;
        
        public RubriqueDocumentComptableResponse() {
        }
        
        public RubriqueDocumentComptableResponse(DevExpTempTest.RDCService.RubriqueDocumentComptableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RubriqueDocumentComptableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RubriqueDocumentComptableResult;
        
        public RubriqueDocumentComptableResponseBody() {
        }
        
        public RubriqueDocumentComptableResponseBody(string RubriqueDocumentComptableResult) {
            this.RubriqueDocumentComptableResult = RubriqueDocumentComptableResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SelectFromRDCSoapChannel : DevExpTempTest.RDCService.SelectFromRDCSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelectFromRDCSoapClient : System.ServiceModel.ClientBase<DevExpTempTest.RDCService.SelectFromRDCSoap>, DevExpTempTest.RDCService.SelectFromRDCSoap {
        
        public SelectFromRDCSoapClient() {
        }
        
        public SelectFromRDCSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SelectFromRDCSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelectFromRDCSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelectFromRDCSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DevExpTempTest.RDCService.HelloWorldResponse DevExpTempTest.RDCService.SelectFromRDCSoap.HelloWorld(DevExpTempTest.RDCService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DevExpTempTest.RDCService.HelloWorldRequest inValue = new DevExpTempTest.RDCService.HelloWorldRequest();
            inValue.Body = new DevExpTempTest.RDCService.HelloWorldRequestBody();
            DevExpTempTest.RDCService.HelloWorldResponse retVal = ((DevExpTempTest.RDCService.SelectFromRDCSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DevExpTempTest.RDCService.HelloWorldResponse> DevExpTempTest.RDCService.SelectFromRDCSoap.HelloWorldAsync(DevExpTempTest.RDCService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<DevExpTempTest.RDCService.HelloWorldResponse> HelloWorldAsync() {
            DevExpTempTest.RDCService.HelloWorldRequest inValue = new DevExpTempTest.RDCService.HelloWorldRequest();
            inValue.Body = new DevExpTempTest.RDCService.HelloWorldRequestBody();
            return ((DevExpTempTest.RDCService.SelectFromRDCSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DevExpTempTest.RDCService.RubriqueDocumentComptableResponse DevExpTempTest.RDCService.SelectFromRDCSoap.RubriqueDocumentComptable(DevExpTempTest.RDCService.RubriqueDocumentComptableRequest request) {
            return base.Channel.RubriqueDocumentComptable(request);
        }
        
        public string RubriqueDocumentComptable(int _latestId) {
            DevExpTempTest.RDCService.RubriqueDocumentComptableRequest inValue = new DevExpTempTest.RDCService.RubriqueDocumentComptableRequest();
            inValue.Body = new DevExpTempTest.RDCService.RubriqueDocumentComptableRequestBody();
            inValue.Body._latestId = _latestId;
            DevExpTempTest.RDCService.RubriqueDocumentComptableResponse retVal = ((DevExpTempTest.RDCService.SelectFromRDCSoap)(this)).RubriqueDocumentComptable(inValue);
            return retVal.Body.RubriqueDocumentComptableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DevExpTempTest.RDCService.RubriqueDocumentComptableResponse> DevExpTempTest.RDCService.SelectFromRDCSoap.RubriqueDocumentComptableAsync(DevExpTempTest.RDCService.RubriqueDocumentComptableRequest request) {
            return base.Channel.RubriqueDocumentComptableAsync(request);
        }
        
        public System.Threading.Tasks.Task<DevExpTempTest.RDCService.RubriqueDocumentComptableResponse> RubriqueDocumentComptableAsync(int _latestId) {
            DevExpTempTest.RDCService.RubriqueDocumentComptableRequest inValue = new DevExpTempTest.RDCService.RubriqueDocumentComptableRequest();
            inValue.Body = new DevExpTempTest.RDCService.RubriqueDocumentComptableRequestBody();
            inValue.Body._latestId = _latestId;
            return ((DevExpTempTest.RDCService.SelectFromRDCSoap)(this)).RubriqueDocumentComptableAsync(inValue);
        }
    }
}
