//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpTempTest.bonLivraisonWSReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="bonLivraisonWSReference.bonLivraisonWSSoap")]
    public interface bonLivraisonWSSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément selectAllFromBonLivraisonResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectAllFromBonLivraison", ReplyAction="*")]
        DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonResponse selectAllFromBonLivraison(DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectAllFromBonLivraison", ReplyAction="*")]
        System.Threading.Tasks.Task<DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonResponse> selectAllFromBonLivraisonAsync(DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectAllFromBonLivraisonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectAllFromBonLivraison", Namespace="http://tempuri.org/", Order=0)]
        public DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonRequestBody Body;
        
        public selectAllFromBonLivraisonRequest() {
        }
        
        public selectAllFromBonLivraisonRequest(DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class selectAllFromBonLivraisonRequestBody {
        
        public selectAllFromBonLivraisonRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectAllFromBonLivraisonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectAllFromBonLivraisonResponse", Namespace="http://tempuri.org/", Order=0)]
        public DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonResponseBody Body;
        
        public selectAllFromBonLivraisonResponse() {
        }
        
        public selectAllFromBonLivraisonResponse(DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectAllFromBonLivraisonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectAllFromBonLivraisonResult;
        
        public selectAllFromBonLivraisonResponseBody() {
        }
        
        public selectAllFromBonLivraisonResponseBody(string selectAllFromBonLivraisonResult) {
            this.selectAllFromBonLivraisonResult = selectAllFromBonLivraisonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface bonLivraisonWSSoapChannel : DevExpTempTest.bonLivraisonWSReference.bonLivraisonWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class bonLivraisonWSSoapClient : System.ServiceModel.ClientBase<DevExpTempTest.bonLivraisonWSReference.bonLivraisonWSSoap>, DevExpTempTest.bonLivraisonWSReference.bonLivraisonWSSoap {
        
        public bonLivraisonWSSoapClient() {
        }
        
        public bonLivraisonWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public bonLivraisonWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public bonLivraisonWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public bonLivraisonWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonResponse DevExpTempTest.bonLivraisonWSReference.bonLivraisonWSSoap.selectAllFromBonLivraison(DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonRequest request) {
            return base.Channel.selectAllFromBonLivraison(request);
        }
        
        public string selectAllFromBonLivraison() {
            DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonRequest inValue = new DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonRequest();
            inValue.Body = new DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonRequestBody();
            DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonResponse retVal = ((DevExpTempTest.bonLivraisonWSReference.bonLivraisonWSSoap)(this)).selectAllFromBonLivraison(inValue);
            return retVal.Body.selectAllFromBonLivraisonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonResponse> DevExpTempTest.bonLivraisonWSReference.bonLivraisonWSSoap.selectAllFromBonLivraisonAsync(DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonRequest request) {
            return base.Channel.selectAllFromBonLivraisonAsync(request);
        }
        
        public System.Threading.Tasks.Task<DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonResponse> selectAllFromBonLivraisonAsync() {
            DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonRequest inValue = new DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonRequest();
            inValue.Body = new DevExpTempTest.bonLivraisonWSReference.selectAllFromBonLivraisonRequestBody();
            return ((DevExpTempTest.bonLivraisonWSReference.bonLivraisonWSSoap)(this)).selectAllFromBonLivraisonAsync(inValue);
        }
    }
}
