//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpTempTest.RDCHostedWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RDCHostedWebService.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Count", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Count();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Count", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RubriqueDocumentComptable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RubriqueDocumentComptable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RubriqueDocumentComptable", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RubriqueDocumentComptableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_N_RubriqueDocumentComptable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Select_N_RubriqueDocumentComptable(int _NombreDesLignes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_N_RubriqueDocumentComptable", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Select_N_RubriqueDocumentComptableAsync(int _NombreDesLignes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_N_RubriqueDocumentComptableFormaJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Select_N_RubriqueDocumentComptableFormaJSON(int _NombreDesLignes, int _latestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_N_RubriqueDocumentComptableFormaJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> Select_N_RubriqueDocumentComptableFormaJSONAsync(int _NombreDesLignes, int _latestId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : DevExpTempTest.RDCHostedWebService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<DevExpTempTest.RDCHostedWebService.WebService1Soap>, DevExpTempTest.RDCHostedWebService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public int Count() {
            return base.Channel.Count();
        }
        
        public System.Threading.Tasks.Task<int> CountAsync() {
            return base.Channel.CountAsync();
        }
        
        public string RubriqueDocumentComptable() {
            return base.Channel.RubriqueDocumentComptable();
        }
        
        public System.Threading.Tasks.Task<string> RubriqueDocumentComptableAsync() {
            return base.Channel.RubriqueDocumentComptableAsync();
        }
        
        public string Select_N_RubriqueDocumentComptable(int _NombreDesLignes) {
            return base.Channel.Select_N_RubriqueDocumentComptable(_NombreDesLignes);
        }
        
        public System.Threading.Tasks.Task<string> Select_N_RubriqueDocumentComptableAsync(int _NombreDesLignes) {
            return base.Channel.Select_N_RubriqueDocumentComptableAsync(_NombreDesLignes);
        }
        
        public string[] Select_N_RubriqueDocumentComptableFormaJSON(int _NombreDesLignes, int _latestId) {
            return base.Channel.Select_N_RubriqueDocumentComptableFormaJSON(_NombreDesLignes, _latestId);
        }
        
        public System.Threading.Tasks.Task<string[]> Select_N_RubriqueDocumentComptableFormaJSONAsync(int _NombreDesLignes, int _latestId) {
            return base.Channel.Select_N_RubriqueDocumentComptableFormaJSONAsync(_NombreDesLignes, _latestId);
        }
    }
}
